### PR TITLE
Update current analyzers to target Django 1.5

### PR DESCRIPTION
**Pull request by yumike**
Some deprecated (as of Django 1.4) things will be removed in 1.5, so we need to update all current analyzers.

### CODE REVIEW

**Comment by xobb1t** [comment]
Function-based generic views will be removed in Django 1.5 too, may be we should improve description about this fact?

**Comment by yumike** [comment]
@xobb1t, yes, i'll do it. This pull request is not completed yet, i'm working on it.

**Comment by yumike** [comment]
@xobb1t I've done with it, please review.

**Comment by xobb1t** [comment]
Nice, gj! :beer:

**Pull request merged**
